### PR TITLE
update naming conventions

### PR DESCRIPTION
**Pull request by radicalrafi**
-updating to Via currency stantard

### CODE REVIEW

**Comment by romanornr** [comment]
Why do you delete the semi columns? 

https://github.com/viacoin/insight-via-ui/pull/2/files#diff-0c303d77c0747b909cce2a6b104acd29L42

**Comment by romanornr** [comment]
You might want to check LTC first too https://github.com/litecoin-project/insight-lite-ui

**Comment by radicalrafi** [comment]
ESLint Standard removes semi-columns by default as sane/good practice

**Comment by romanornr** [comment]
It will cause merge conflicts.
Never divert from the upstream if it hasn't something to do with the coin it self. 

For fixes & improvements, get it merged to your upstream first. In this case, you should make a pull request for bitpay.

**Pull request closed without merging**
